name: Test

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@opstrace'

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code Base
        uses: github/super-linter@v3.17.1
        env:
          LINTER_RULES_PATH: /
          LOG_LEVEL: 'WARN'
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_STANDARD: false
          FILTER_REGEX_EXCLUDE: .*husky.*
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: npm test
